In [1]:
import pandas as pd
import random

dates = pd.date_range(start="2025-01-01", end="2025-12-31")
categories = ["Food", "Travel", "Shopping", "Rent", "Bills", "Entertainment"]

data = []

for date in dates:
    for i in range(2): 
        data.append([
            date.strftime("%Y-%m-%d"),
            random.choice(categories),
            random.randint(200, 3000)
        ])

df = pd.DataFrame(data, columns=["date", "category", "amount"])

df.to_csv("expense_data_2025.csv", index=False)

print("File Created")
df.head()

File Created

         date  category  amount
0  2025-01-01    Travel    1229
1  2025-01-01  Shopping    2297
2  2025-01-02      Rent    2758
3  2025-01-02    Travel    1960
4  2025-01-03      Rent    1266

In [2]:
df = pd.read_csv("expense_data_2025.csv")
df.shape

(730, 3)

In [9]:
import pandas as pd

df = pd.read_csv("expense_data_2025.csv")
df.head()

         date  category  amount
0  2025-01-01    Travel    1229
1  2025-01-01  Shopping    2297
2  2025-01-02      Rent    2758
3  2025-01-02    Travel    1960
4  2025-01-03      Rent    1266

In [10]:
import pandas as pd
import pyodbc
from sklearn.linear_model import LinearRegression
import numpy as np

In [11]:
import pyodbc

conn = pyodbc.connect(
    'DRIVER={SQL Server};'
    'SERVER=YOUR_SERVER_NAME'
    'DATABASE=ExpenseDB;'
    'Trusted_Connection=yes;'
)

query = """
SELECT * FROM expense_data_2025
"""

df = pd.read_sql(query, conn)

C:\Users\Muneer Khan\AppData\Local\Temp\ipykernel_26844\2941342421.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [12]:
df.head()

         date  category  amount
0  2025-01-01    Travel    1229
1  2025-01-01  Shopping    2297
2  2025-01-02      Rent    2758
3  2025-01-02    Travel    1960
4  2025-01-03      Rent    1266

In [13]:
query = "SELECT * FROM expense_data_2025"

df = pd.read_sql(query, conn)

df.head()

C:\Users\Muneer Khan\AppData\Local\Temp\ipykernel_26844\1503487055.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

         date  category  amount
0  2025-01-01    Travel    1229
1  2025-01-01  Shopping    2297
2  2025-01-02      Rent    2758
3  2025-01-02    Travel    1960
4  2025-01-03      Rent    1266

In [14]:
df['date'] = pd.to_datetime(df['date'])

df['month'] = df['date'].dt.month

monthly = df.groupby('month')['amount'].sum().reset_index()

monthly

    month  amount
0       1   97050
1       2   91169
2       3  105222
3       4   99610
4       5  107720
5       6  105393
6       7   96805
7       8   94693
8       9  106498
9      10   94249
10     11   91240
11     12  104894